import assert from 'node:assert/strict';
import { BENCHMARK_PROJECT } from '../engine/referenceCase';
import { SyncService } from '../services/syncService';
import { contentEqual, projectDifferences } from '../store/sync/projectDifferences';
import { acknowledgeProjectPush, reconcilePulledProjects } from '../store/sync/projectReconciliation';
import { useSimulationStore } from '../store/useSimulationStore';
import { serializeSimulationStore } from '../store/persistence/serializeSimulationStore';
import { featureScope } from '../../shared/applicationFeatures';
const url = 'https://qa.example.invalid';
const user = { id: 'qa', organizationId: 'qa-org', role: 'EDITOR' as const, name: 'Consultor QA', email: 'qa@example.invalid' };
const session = { serverUrl: url, currentUser: user, authToken: 'synthetic', autoSyncEnabled: false, lastSyncTimestamp: null };
const local = { ...structuredClone(BENCHMARK_PROJECT), id: 'qa-conflict', organizationId: user.organizationId, syncServerUrl: url, version: 1, baseVersion: 0, syncStatus: 'pending' as const };
const remote = { ...local, isDeleted: false, baseVersion: 1, syncStatus: 'synced' as const, client: Object.fromEntries(Object.entries(local.client).reverse()) as typeof local.client };
assert.ok(contentEqual({ a: 1, b: [2, 3] }, { b: [2, 3], a: 1 }));
assert.ok(!contentEqual([1, 2], [2, 1]));
assert.equal(projectDifferences(remote, local).length, 0, 'PostgreSQL JSONB key order is not a content change');
assert.equal(reconcilePulledProjects([local], [remote], [], new Set(), url, user.organizationId)[0].syncStatus, 'synced', 'Creation with lost ACK is confirmed by identical authoritative read');
const edited = { ...local, client: { ...local.client, name: 'Cambios locales' } };
assert.equal(reconcilePulledProjects([edited], [remote], [], new Set(), url, user.organizationId)[0].baseVersion, 0, 'Real divergence is not silently rebased');
const diff = projectDifferences(remote, edited)[0];
assert.equal(diff.field, 'Nombre'); assert.equal(diff.formattedNew, 'Cambios locales'); assert.equal(diff.formattedOld, remote.client.name);
assert.equal(reconcilePulledProjects([edited], [], [edited.id], new Set(), url, user.organizationId)[0].syncStatus, 'conflict', 'Remote purge preserves unconfirmed work');
const forkAck = acknowledgeProjectPush([local], [local], [{ id: 'qa-fork-confirmed', originalId: local.id, status: 'conflict', serverVersion: 2, localVersion: 1, serverProject: { ...remote, id: 'qa-fork-confirmed', version: 2 } }], url, user.organizationId);
assert.equal(forkAck.projects[0].id, 'qa-fork-confirmed'); assert.equal(forkAck.conflicts[0].local.id, 'qa-fork-confirmed'); assert.equal(forkAck.idChanges[local.id], 'qa-fork-confirmed');
const initial = useSimulationStore.getState();
const fetchOriginal = globalThis.fetch;
const pullOriginal = SyncService.pullProjects;
try {
  // Legacy successful ACK requires canonical read-back, not guessing from the payload.
  globalThis.fetch = async (input) => String(input).endsWith('/push') ? Response.json({ success: true, results: [{ id: local.id, status: 'created', version: 1 }] }) : Response.json({ success: true, projects: [remote] });
  const result = await SyncService.pushProjects(url, 'synthetic', [local]);
  assert.equal(result.success, true); assert.equal(result.results?.[0].status, 'created');
  const duringSend = { ...local, client: { ...local.client, name: 'Edición durante envío' } };
  const ack = acknowledgeProjectPush([duringSend], [local], result.results!, url, user.organizationId).projects[0];
  assert.equal(ack.client.name, duringSend.client.name); assert.equal(ack.syncStatus, 'pending'); assert.equal(ack.baseVersion, 1);
  globalThis.fetch = async (input) => String(input).endsWith('/push') ? Response.json({ success: true, results: [{ id: local.id, status: 'created', version: 1 }] }) : Response.json({ success: true, projects: [{ ...remote, version: 2 }] });
  assert.equal((await SyncService.pushProjects(url, 'synthetic', [local])).results?.[0].status, 'conflict', 'A concurrent change during readback stays reviewable');
  globalThis.fetch = async (input) => String(input).endsWith('/push') ? Response.json({ success: true, results: [{ id: local.id, status: 'created', version: 1 }] }) : new Response('', { status: 503 });
  const sparse = await SyncService.pushProjects(url, 'synthetic', [local]);
  assert.equal(sparse.success, true);
  const deferred = acknowledgeProjectPush([local], [local], sparse.results!, url, user.organizationId).projects[0];
  assert.equal(deferred.syncStatus, 'pending'); assert.equal(deferred.pendingCanonicalAck?.version, 1);
  assert.equal(reconcilePulledProjects([deferred], [], [], new Set(), url, user.organizationId)[0].pendingCanonicalAck?.version, 1);
  assert.equal(reconcilePulledProjects([deferred], [remote], [], new Set(), url, user.organizationId)[0].syncStatus, 'synced');
  globalThis.fetch = async (input) => String(input).endsWith('/push') ? Response.json({ success: true, results: [{ id: 'qa-fork-readback', originalId: local.id, status: 'forked', version: 1 }] }) : new Response('', { status: 503 });
  const sparseFork = await SyncService.pushProjects(url, 'synthetic', [local]);
  const forkReceipt = acknowledgeProjectPush([edited], [local], sparseFork.results!, url, user.organizationId).projects[0];
  assert.equal(forkReceipt.id, 'qa-fork-readback'); assert.equal(forkReceipt.client.name, edited.client.name);
  assert.equal(forkReceipt.baseVersion, 1); assert.equal(forkReceipt.pendingCanonicalAck?.version, 1);
  const serializedReceipt = JSON.parse(JSON.stringify(forkReceipt));
  assert.equal(reconcilePulledProjects([serializedReceipt], [], [], new Set(), url, user.organizationId)[0].pendingCanonicalAck?.version, 1);
  const afterReadback = reconcilePulledProjects([serializedReceipt], [{ ...remote, id: forkReceipt.id }], [], new Set(), url, user.organizationId)[0];
  assert.equal(afterReadback.pendingCanonicalAck, undefined); assert.equal(afterReadback.syncStatus, 'pending'); assert.equal(afterReadback.baseVersion, 1);

  const conflicted = { ...edited, syncStatus: 'conflict' as const };
  useSimulationStore.setState({ syncSettings: session, projects: [conflicted], projectConflicts: {}, snapshotsByProject: {}, activeConflict: null });
  initial.setActiveConflict({ projectId: local.id, localVersion: 0, serverVersion: 1, localProject: conflicted, serverProject: remote, lastModifiedByName: '', lastModifiedAt: '', diffs: projectDifferences(remote, conflicted) });
  initial.setActiveConflict(null);
  const scope = featureScope(url, user.organizationId);
  assert.ok(serializeSimulationStore(useSimulationStore.getState()).projectConflicts[scope + '|' + local.id], 'Closing preserves durable conflict');
  SyncService.pullProjects = async () => ({ success: true, projects: [remote] });
  assert.equal((await initial.openProjectConflict(local.id)).success, true);
  assert.equal(useSimulationStore.getState().activeConflict?.localVersion, 0);
  initial.resolveConflict('fork');
  const copies = useSimulationStore.getState().projects;
  assert.equal(copies.length, 2); assert.equal(copies[0].syncStatus, 'synced'); assert.equal(copies[1].baseVersion, 0); assert.equal(copies[1].client.name, 'Cambios locales (copia)');
  assert.equal(useSimulationStore.getState().snapshotsByProject[local.id][0].data.client.name, 'Cambios locales');
  assert.equal(Object.keys(useSimulationStore.getState().projectConflicts).length, 0);
  assert.notEqual(copies[1].client.projectId, copies[0].client.projectId);
  assert.notEqual(copies[1].client.quoteNumber, copies[0].client.quoteNumber);
  assert.equal(copies[1].authorId, user.id);
  useSimulationStore.setState({ projects: [conflicted], syncEquipmentWithServer: async () => ({success:true,message:'QA'}), isSyncing:false });
  initial.setActiveConflict({ projectId: local.id, localVersion: 0, serverVersion: 1, localProject: conflicted, serverProject: remote, lastModifiedByName: '', lastModifiedAt: '', diffs: [] });
  SyncService.pullProjects = async () => ({ success: true, projects: [], deletedIds: [local.id] });
  await initial.syncProjectsWithServer();
  assert.equal(useSimulationStore.getState().activeConflict?.reason, 'deleted', 'An open modal must follow a fresh tombstone');
  initial.resolveConflict('accept_server');
  assert.equal(useSimulationStore.getState().projects[0].client.name, conflicted.client.name, 'A stale modal cannot discard deleted-cloud local work');
  assert.equal((await initial.openProjectConflict(local.id)).success, true);
  assert.equal(useSimulationStore.getState().activeConflict?.reason, 'deleted');
  initial.resolveConflict('accept_server');
  assert.equal(useSimulationStore.getState().projects[0].syncStatus, 'conflict');
  initial.resolveConflict('fork');
  assert.equal(useSimulationStore.getState().projects.length, 1);
  assert.notEqual(useSimulationStore.getState().projects[0].id, local.id);
  assert.equal(useSimulationStore.getState().projects[0].isDeleted, false);

  useSimulationStore.setState({ projects: [conflicted], activeConflict: null, syncSettings: session });
  let finish!: (result: any) => void;
  SyncService.pullProjects = () => new Promise(resolve => { finish = resolve; });
  const opening = initial.openProjectConflict(local.id);
  initial.logoutUser(); initial.setSyncSettings(session);
  finish({ success: true, projects: [remote] });
  assert.equal((await opening).success, false, 'Old session readback cannot open a conflict');
  assert.equal(useSimulationStore.getState().activeConflict, null);

  SyncService.pullProjects = async () => ({ success: true, projects: [remote] });
  useSimulationStore.setState({ syncSettings: { ...session, currentUser: { ...user, role: 'VIEWER' } } });
  await initial.openProjectConflict(local.id);
  initial.resolveConflict('keep_local');
  assert.equal(useSimulationStore.getState().projects[0].syncStatus, 'conflict', 'Viewer cannot queue an overwrite');
  initial.resolveConflict('accept_server');
  assert.equal(useSimulationStore.getState().projects[0].syncStatus, 'synced', 'Viewer may accept an authorized server read');
} finally {
  globalThis.fetch = fetchOriginal; SyncService.pullProjects = pullOriginal; useSimulationStore.setState(initial, true);
}
console.log('Legacy ACK recovery, semantic differences, durable conflicts, checkpoints and session isolation passed.');
