import assert from 'node:assert/strict';
import {normalizeProposalDraft,PROPOSAL_JSON_SCHEMA} from '../../shared/aiProposal';
import {requestGeminiJson,GeminiRequestError} from '../../shared/geminiTransport';
import {buildAITariffContext} from '../utils/aiTariffContext';
import {createAIProposalBase,prepareProposalDraftProject} from '../utils/proposalDraftProject';
import {calculateProjectFinancialSummary} from '../engine/financeEngine';
import {BENCHMARK_PROJECT} from '../engine/referenceCase';
import {useSimulationStore} from '../store/useSimulationStore';
const state=useSimulationStore.getState();
const catalog=structuredClone(state.equipmentCatalog);
const panel=catalog.find(e=>e.type==='panel')!,inverter=catalog.find(e=>e.type==='inverter')!;
const context={province:'Santiago',annualSpecificYieldKWhPerKWp:1500,tariffReference:buildAITariffContext(state.tariffMatrix),commercial:{pricingMode:'cost_matrix' as const,markupPct:28,installationUnitPriceUSD:170,customItems:[{id:'old',description:'Protección',quantity:1,unitPriceUSD:25,exonerateITBIS:false,applyMargin:true}],customDiscounts:[]}};
const input={clientName:'QA comercial',province:'Santiago',distributor:'EDESUR',tariffCode:'BTS2',averageMonthlyKWh:500,panels:[{equipmentId:panel.id,quantity:10,unitPriceUSD:0}],inverters:[{equipmentId:inverter.id,quantity:1,unitPriceUSD:1000}],batteries:[],hasBattery:false,commercial:{marginOnSalePct:30,installationTotalUSD:300,customDiscounts:[{description:'Cortesía',type:'percentage',value:10,target:'general'}]}};
const normalized=normalizeProposalDraft(input,catalog,context);
assert.equal(normalized.requiresReview,false);
assert.equal(normalized.panels?.[0].unitPriceUSD,0,'zero purchase override preserved');
assert.equal(normalized.panels?.[0].priceSource,'manual');
assert.equal(normalized.autoSupplierPricing,false);
assert.equal(normalized.commercial?.markupPct,undefined,'sale margin replaces contextual markup');
assert.equal(normalized.commercial?.installationUnitPriceUSD,undefined,'total labor replaces contextual unit labor');
assert.equal(normalized.commercial?.customItems?.[0].id,'old','omission preserves extras');
assert(Math.abs(normalized.targetMarginPct! - 42.857142857)<1e-6);
const again=normalizeProposalDraft(normalized,catalog,context);
assert.deepEqual(again.commercial,normalized.commercial);
assert.deepEqual(again.panels,normalized.panels);
const base=createAIProposalBase(BENCHMARK_PROJECT,state.defaultSimulationSettings,'Santiago');
assert.equal(base.financials.customITBISSavedUSD,undefined);
assert.equal(base.financials.customLey5707CreditUSD,undefined);
assert.equal(base.financials.customCostUSD,undefined);
const prepared=prepareProposalDraftProject(base,again,state.tariffMatrix,{isNew:true,defaultBatteryDOD:state.defaultSimulationSettings.defaultBatteryDOD});
assert.equal(prepared.specs.installationUnitPriceUSD!*(panel.powerW!*10/1000),300);
assert.equal(prepared.financials.customItems?.[0].unitPriceUSD,25);
assert.equal(prepared.financials.customDiscounts?.[0].value,10);
const original={...state};
useSimulationStore.setState({equipmentCatalog:catalog,projects:[],activeProjectId:'',syncSettings:{...state.syncSettings,authToken:null,currentUser:null,autoSyncEnabled:false}});
useSimulationStore.getState().applyExtractedInvoice(again,true);
const applied=useSimulationStore.getState().projects[0];
for(const mode of ['legacy','self_consumption'] as const){
  const preview=calculateProjectFinancialSummary(prepared,mode),actual=calculateProjectFinancialSummary(applied,mode);
  assert.equal(actual.contractPriceUSD,preview.contractPriceUSD,'preview and apply use one adapter');
  assert.equal(actual.itbisSavedUSD,preview.itbisSavedUSD,'no inherited benchmark fiscal override');
  assert.deepEqual(actual.monthlyBreakdown,preview.monthlyBreakdown);
}
assert.deepEqual(useSimulationStore.getState().equipmentCatalog,catalog,'proposal pricing cannot change catalog');
useSimulationStore.setState(original);
assert.equal(normalizeProposalDraft({...again,commercial:{...again.commercial,customItems:[],customDiscounts:[]}},catalog,context).commercial?.customItems?.length,0);
assert.equal(normalizeProposalDraft({...again,commercial:{marginOnSalePct:100}},catalog,context).requiresReview,true);
assert.equal(normalizeProposalDraft({...again,panels:[{...again.panels![0],unitPriceUSD:-1}]},catalog,context).requiresReview,true);
assert.equal(normalizeProposalDraft({...again,commercial:{customDiscounts:[{description:'Bad',type:'percentage',value:101,target:'general'}]}},catalog,context).requiresReview,true);
let calls=0;
const recovered=await requestGeminiJson({apiKey:'synthetic',model:'gemini-3.8-flash',body:{generationConfig:{maxOutputTokens:16384}}},async(_url,body:any)=>{
 calls++;assert.equal(body.generationConfig.thinkingConfig.thinkingLevel,'low');
 assert.equal(body.generationConfig.maxOutputTokens,calls===1?16384:32768);
 return {candidates:[{finishReason:calls===1?'MAX_TOKENS':'STOP',content:{parts:[{text:'{}'}]}}]};
});assert.equal(calls,2);assert(recovered.modelWarning);
calls=0;await assert.rejects(()=>requestGeminiJson({apiKey:'synthetic',body:{}},async()=>{calls++;return {candidates:[{finishReason:'MAX_TOKENS'}]};}),/Reduce/);assert.equal(calls,2);
calls=0;await assert.rejects(()=>requestGeminiJson({apiKey:'synthetic',body:{}},async()=>{calls++;if(calls===1)throw new GeminiRequestError('transient',503);return {candidates:[{finishReason:'MAX_TOKENS'}]};}),/Reduce/);assert.equal(calls,2,'transient plus truncation cannot create third paid request');
calls=0;await assert.rejects(()=>requestGeminiJson({apiKey:'synthetic',body:{}},async()=>{calls++;throw new GeminiRequestError('quota',429);}),/quota/);assert.equal(calls,1);
await requestGeminiJson({apiKey:'synthetic',model:'gemini-2.5-flash',body:{}},async(_url,body:any)=>{assert.equal(body.generationConfig.thinkingConfig.thinkingBudget,1024);assert.equal(body.generationConfig.thinkingConfig.thinkingLevel,undefined);return {candidates:[{finishReason:'STOP'}]};});
console.log('Commercial overrides, clean defaults, shared preview/application and bounded MAX_TOKENS recovery passed.');
const bad=normalizeProposalDraft({...input,panels:[{equipmentId:panel.id,quantity:1.5,unitPriceUSD:-1}],commercial:{marginOnSalePct:100}},catalog,context);
const badAgain=normalizeProposalDraft(bad,catalog,context);
assert.equal(badAgain.requiresReview,true,'invalid edits must remain invalid across normalization');
assert(badAgain.validationIssues?.some(i=>i.code==='invalid_panel_price'));
assert(badAgain.validationIssues?.some(i=>i.code==='invalid_marginOnSalePct'));
assert(badAgain.validationIssues?.some(i=>i.code==='invalid_panel_count'));
const followup=normalizeProposalDraft({...input,commercial:undefined,panels:[{equipmentId:panel.id,quantity:10}]},catalog,{...context,currentDraft:normalized});
assert.equal(followup.commercial?.marginOnSalePct,30);
assert.equal(followup.commercial?.markupPct,undefined);
assert.equal(followup.commercial?.customDiscounts?.[0].value,10);
assert.equal(followup.panels?.[0].unitPriceUSD,0);
const conflicting=normalizeProposalDraft({...input,panels:[{equipmentId:panel.id,quantity:5,unitPriceUSD:100},{equipmentId:panel.id,quantity:5,unitPriceUSD:200}]},catalog,context);
assert.equal(conflicting.panels?.length,2,'conflicting commercial rows cannot collapse');
assert.equal(normalizeProposalDraft(conflicting,catalog,context).requiresReview,true);
assert.equal(normalizeProposalDraft({...input,commercial:{pricingMode:'direct_watt',pricePerWattUSD:0}},catalog,context).requiresReview,true);
const corrected=normalizeProposalDraft({...input,commercial:{markupPct:30}},catalog,{...context,currentDraft:{commercial:{markupPct:-5}}});
assert.equal(corrected.requiresReview,false,'a valid correction removes the old error in the first pass');

// Gemini must represent every commercial condition instead of legally omitting requested changes.
assert(PROPOSAL_JSON_SCHEMA.required.includes('commercial'));
assert(PROPOSAL_JSON_SCHEMA.properties.commercial.required.includes('installationTotalUSD'));
const nullableCommercial=normalizeProposalDraft({...input,commercial:{markupPct:40,marginOnSalePct:null,installationTotalUSD:500,installationUnitPriceUSD:null,customItems:[],customDiscounts:[]}},catalog,context);
assert.equal(nullableCommercial.commercial?.markupPct,40);
assert.equal(nullableCommercial.commercial?.installationTotalUSD,500);
assert.equal(nullableCommercial.commercial?.installationUnitPriceUSD,undefined);
assert.equal(nullableCommercial.commercial?.marginOnSalePct,undefined);
assert.equal(nullableCommercial.requiresReview,false);
assert.deepEqual(normalizeProposalDraft(nullableCommercial,catalog,context).commercial,nullableCommercial.commercial);

for(const field of ['distributor','tariffCode','energyCostPerKWhDOP','consumptionSource']) assert(PROPOSAL_JSON_SCHEMA.required.includes(field),'required supply/provenance prevents silently omitted user data');
const realFixture=normalizeProposalDraft({...input,commercial:{markupPct:40,installationTotalUSD:500,customItems:[{description:'Protecciones',quantity:1,unitPriceUSD:250,exonerateITBIS:false,applyMargin:true}],customDiscounts:[{description:'Cortesía',type:'fixed',value:100,target:'general'}]},consumptionSource:'estimated',monthlyConsumptionKWh:Array(12).fill(900),energyCostPerKWhDOP:13.26},catalog,context);
assert.equal(realFixture.requiresReview,false);
assert(realFixture.validationIssues?.some(i=>i.code==='estimated_consumption'&&i.severity==='warning'));
