export const INVOICE_JSON_SCHEMA = {
  type: 'OBJECT',
  properties: {
    clientName: { type: 'STRING' },
    companyName: { type: 'STRING' },
    nic: { type: 'STRING' },
    nis: { type: 'STRING' },
    circuit: { type: 'STRING' },
    rnc: { type: 'STRING' },
    contractNumber: { type: 'STRING' },
    eNCF: { type: 'STRING' },
    address: { type: 'STRING' },
    province: { type: 'STRING' },
    municipality: { type: 'STRING' },
    phone: { type: 'STRING' },
    email: { type: 'STRING' },
    distributor: {
      type: 'STRING',
      enum: ['EDEESTE', 'EDESUR', 'EDENORTE', 'CEPM'],
    },
    tariffCode: { type: 'STRING' },
    energyCostPerKWhDOP: { type: 'NUMBER' },
    marginalRateDOP: { type: 'NUMBER' },
    fixedChargeDOP: { type: 'NUMBER' },
    peakDemandKW: { type: 'NUMBER' },
    demandCostPerKWDOP: { type: 'NUMBER' },
    meterNumber: { type: 'STRING' },
    voltagePhase: { type: 'STRING' },
    powerFactor: { type: 'NUMBER' },
    billingDays: { type: 'NUMBER' },
    totalBilledAmountDOP: { type: 'NUMBER' },
    totalWithoutSubsidyDOP: { type: 'NUMBER' },
    governmentSubsidyDOP: { type: 'NUMBER' },
    monthlyConsumptionKWh: {
      type: 'ARRAY',
      items: { type: 'NUMBER' },
    },
    annualConsumptionKWh: { type: 'NUMBER' },
    averageMonthlyKWh: { type: 'NUMBER' },
    currentBilledKWh: { type: 'NUMBER' },
    matchedPanelId: { type: 'STRING' },
    matchedPanelModel: { type: 'STRING' },
    matchedPanelWatts: { type: 'NUMBER' },
    matchedPanelCount: { type: 'NUMBER' },
    matchedInverterId: { type: 'STRING' },
    matchedInverterModel: { type: 'STRING' },
    matchedInverterPowerKW: { type: 'NUMBER' },
    matchedInverterCount: { type: 'NUMBER' },
    hasBattery: { type: 'BOOLEAN' },
    matchedBatteryId: { type: 'STRING' },
    matchedBatteryModel: { type: 'STRING' },
    matchedBatteryCapacityKWh: { type: 'NUMBER' },
    matchedBatteryCount: { type: 'NUMBER' },
    targetMarginPct: { type: 'NUMBER' },
    specialTechnicalNotes: { type: 'STRING' },
    aiReasoningSummary: { type: 'STRING' },
    confidenceScore: { type: 'NUMBER' },
    notes: { type: 'STRING' },
    equipmentSubstitutions: {
      type: 'ARRAY',
      items: {
        type: 'OBJECT',
        properties: {
          type: { type: 'STRING', enum: ['panel', 'inverter', 'battery'] },
          requestedModel: { type: 'STRING' },
          selectedModel: { type: 'STRING' },
          reason: { type: 'STRING' },
        },
        required: ['type', 'requestedModel', 'selectedModel', 'reason'],
      },
    },
  },
  required: [
    'clientName',
    'distributor',
    'tariffCode',
    'monthlyConsumptionKWh',
    'annualConsumptionKWh',
    'averageMonthlyKWh',
    'confidenceScore',
  ],
};
